"""Online dataset generation via random walks (no human knowledge).

Starting from the solved state we apply random quarter-turn moves and record
the (state, depth) pair at every prefix.  Depth is the number of moves used to
reach that state, which is a noisy but strongly correlated proxy for the true
distance-to-solved ("diffusion distance").  This is what makes the whole method
unsupervised: labels are generated by the walk, never by a solver.
"""
from __future__ import annotations

import torch
import numpy as np

from . import state as C


def generate_random_walks(num_walks: int, k_max: int, device=None, exclude_same_face=True):
    """Generate random walks from the solved state.

    Returns
    -------
    states: int64 tensor (num_walks * k_max, 54) of sticker states
    depths: int64 tensor (num_walks * k_max,)  of walk depths k in 1..k_max
    """
    device = device or torch.device("cpu")
    k_max = int(k_max)
    num_walks = int(num_walks)
    if num_walks < 1:
        raise ValueError("num_walks must be >= 1")

    # set up batched walks
    solved = C.solved_stickers()
    cur = torch.tensor(solved, dtype=torch.int64, device=device).unsqueeze(0).repeat(num_walks, 1)
    last_face = torch.full((num_walks,), -1, dtype=torch.int64, device=device)

    move_perm = torch.tensor(C.MOVE_PERM, dtype=torch.int64, device=device)  # (12,54)

    # We record all prefixes, yielding exactly num_walks*k_max pairs.
    states = [None] * k_max
    depths = [None] * k_max
    for step in range(1, k_max + 1):
        # choose a move, avoiding the same face as the previous move (prevents
        # trivial "R R'" self-cancel noise)
        if exclude_same_face:
            # rand offset in 1..5 -> guaranteed different face
            offs = torch.randint(1, 6, size=(num_walks,), device=device)
            faces = torch.where(last_face >= 0, (last_face + offs) % 6, torch.randint(0, 6, size=(num_walks,), device=device))
        else:
            faces = torch.randint(0, 6, size=(num_walks,), device=device)
        dirs = torch.randint(0, 2, size=(num_walks,), device=device)
        move_idx = faces * 2 + dirs                       # 0..11

        # apply moves
        cur = cur.gather(1, move_perm[move_idx])           # (num_walks,54)
        last_face = faces

        states[step - 1] = cur
        depths[step - 1] = torch.full((num_walks,), step, dtype=torch.int64, device=cur.device)

    states = torch.cat(states, dim=0)   # (num_walks*k_max, 54)
    depths = torch.cat(depths, dim=0)   # (num_walks*k_max,)
    return states, depths


def make_batch(num_walks, k_max, device=None):
    """Return (input_onehot_float, depth_float) ready for the network."""
    device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")
    states, depths = generate_random_walks(num_walks, k_max, device=device)
    x = C.state_to_input(states)        # (n, 324) float
    y = depths.float()
    return x, y


def make_random_scrambles(num_states, k_len=60, device=None):
    """Generate `num_states` independently scrambled states (full-length walks).

    Returns int64 tensor (num_states, 54)."""
    device = device or torch.device("cpu")
    states, _ = generate_random_walks(num_states, k_len, device=device)
    return states


def generate_scrambles(num, min_len=20, max_len=60, device=None, rng=None):
    """Return `num` independently scrambled states (int64 tensor (num, 54)).

    Each state is produced by a random walk whose length is drawn uniformly from
    [min_len, max_len], giving a spread over a wide difficulty band (an
    "arbitrary scramble").  Reuses the batched walk generator.
    """
    import numpy as np
    device = device or torch.device("cpu")
    rng = rng or np.random.default_rng()
    max_len = int(max_len)
    min_len = min(int(min_len), max_len)
    num = int(num)
    states, _ = generate_random_walks(num, max_len, device=device)
    states = states.reshape(max_len, num, 54)  # [depth-1, walk, :]
    lengths = rng.integers(int(min_len), max_len + 1, size=num)   # 1-based depth
    idx = torch.arange(num, device=device)
    sel = states[torch.tensor(lengths, device=device) - 1, idx, :]
    return sel
